ESICFeedback/urls.py
from django.contrib import admin
from django.urls import path,include
import Feedback.urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('Feedback/',include(Feedback.urls))
]

Feedback/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

urlpatterns = [
    path('',views.homepage,name="homepage"),
    path('patientcomplaints/',views.patientcomplaints,name="patientcomplaints"),
    path('patientINcomplaints/',views.patientINcomplaints,name="patientINcomplaints"),
    path('Feedbackform/',views.Feedbackform,name="Feedbackform"),
    path('patientfeedback/',views.patientfeedback,name="patientfeedback"),
    path('patientcomplaints/<patient_id>/',views.change,name="change"),
    path('patientINcomplaints/<patient_id>/',views.change2,name="change2"),
    path('patientcomplaints/<patient_id>/',views.forward,name="forward"),
    path('patientINcomplaints/<patient_id>/',views.forward,name="forward2"),
    path('patientINfeedback/',views.patientINfeedback,name="patientINfeedback"),
    path('admindashboard/',views.dashboard,name="dashboard"),
    path('thankyou/',views.thankyou,name="thankyou"),
    path('HODSignUp/',views.addHOD,name="addHOD"),
    path('MinisterSignUp/',views.addMinister,name="addMinister"),
    path('login/',views.login,name="login"),
    path('logout/',views.logout,name="logout"),
    path('IPDFeedbackform/',views.IPDFeedbackForm,name="IPDFeedbackForm"),
    path('askingpage/',views.askingpage,name="askingpage"),
    path('adminaskingpage/',views.adminaskingpage,name="adminaskingpage"),
    path('otpverify/',views.verifyotp,name="verifyotp"),

]

Feedback/models.py
from django.db import models

class Patient(models.Model):
<<<<<<< HEAD
    mobile_number=models.CharField(max_length=100,null=True,default="0")
    ip_number=models.CharField(max_length=101,null=True,default="0")
=======
    mobile_number=models.CharField(max_length=100,primary_key=True,null=False,default=0)
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
    Rating=models.CharField(max_length=10,null=True,default=None,blank=True)
    sandf=models.CharField(max_length=50,null=True,default=None,blank=False)
    department=models.CharField(max_length=50,null=True,default=None,blank=False)
    AreaofIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    Hygiene=models.CharField(max_length=5,default=None,blank=True,null=True)
    DoctorBehaviour=models.CharField(max_length=5,default=None,blank=True,null=True)
    WaitingTime=models.CharField(max_length=5,default=None,blank=True,null=True)
    Pharmacy=models.CharField(max_length=5,default=None,blank=True,null=True)
    Nurse=models.CharField(max_length=5,default=None,blank=True,null=True)
    explanation=models.CharField(max_length=200,null=True,blank=True,default=None)
    Status=models.CharField(max_length=10,null=True,blank=True,default="0")
    otp=models.CharField(max_length=6,null=True,blank=True,default=None)

    def __str__(self):
        return self.mobile_number

class PatientIN(models.Model):
<<<<<<< HEAD
    mobile_number=models.CharField(max_length=100,null=False,default="0")
    ip_number=models.CharField(max_length=101,null=False,default="0")
=======
    mobile_number=models.CharField(max_length=100,primary_key=True,null=False,default=0)
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
    Rating=models.CharField(max_length=10,null=True,default=None,blank=True)
    sandf=models.CharField(max_length=50,null=True,default=None,blank=False)
    department=models.CharField(max_length=50,null=True,default=None,blank=False)
    AreaofIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    AdmissionIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    NurseIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    DoctorIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    AllotmentIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    DischargeIssue=models.CharField(max_length=40,default=None,null=True,blank=True)
    explanation=models.CharField(max_length=200,null=True,blank=True,default=None)
    Status=models.CharField(max_length=10,null=True,blank=True,default="0")
    otp=models.CharField(max_length=6,null=True,blank=True,default=None)
    
    def __str__(self):
        return self.mobile_number


class HOD(models.Model):
    email=models.CharField(max_length=100,primary_key=True,default=None)
    password=models.CharField(max_length=20,default=None,blank=False)

    def __str__(self):
        return self.email

class Minister(models.Model):
    email=models.CharField(max_length=100,primary_key=True,default=None)
    password=models.CharField(max_length=20,default=None,blank=False)

    def __str__(self):
        return self.email
        
        

Feedback/forms.py
from django import forms
from .import models
from nocaptcha_recaptcha.fields import NoReCaptchaField

# Creating form classes 

class PatientUpdationForm(forms.Form):
    Rating=forms.CharField(required=False)
    sandf=forms.CharField(required=False)
    department=forms.CharField(required=False)
    AreaofIssue=forms.CharField(required=False)
    Hygiene=forms.CharField(required=False)
    DoctorBehaviour=forms.CharField(required=False)
    WaitingTime=forms.CharField(required=False)
    Pharmacy=forms.CharField(required=False)
    Nurse=forms.CharField(required=False)
    explanation=forms.CharField(required=False)

class INPatientUpdationForm(forms.Form):
    Rating=forms.CharField(required=False)
    sandf=forms.CharField(required=False)
    department=forms.CharField(required=False)
    AreaofIssue=forms.CharField(required=False)   
    AdmissionIssue=forms.CharField(required=False)
    NurseIssue=forms.CharField(required=False)
    DoctorIssue=forms.CharField(required=False)
    AllotmentIssue=forms.CharField(required=False)
    DischargeIssue=forms.CharField(required=False)
    explanation=forms.CharField(required=False)
    

class PatientCreationForm(forms.Form):
    mobile_number=forms.CharField()
<<<<<<< HEAD
    ip_number=forms.CharField()
=======
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
    captcha = NoReCaptchaField(gtag_attrs={'data-theme':'dark'})



class AdminCreationForm(forms.Form):
    email=forms.CharField()
    password=forms.CharField()
    


class UserLoginForm(forms.Form):
    email=forms.CharField()
    password=forms.CharField()



class OTPVerifyForm(forms.Form):
    otp=forms.CharField()
    


    

Feedback/views.py
from django.shortcuts import render,redirect
from .forms import PatientCreationForm,PatientUpdationForm,AdminCreationForm,UserLoginForm,INPatientUpdationForm,OTPVerifyForm
from . models import Patient,HOD,PatientIN,Minister
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.core.mail import send_mail
import math,random
#from django.generic.views import CreateView
from django.views.generic import View



def homepage(request):
<<<<<<< HEAD
    totalfeedbacks=(len(Patient.objects.all())+len(PatientIN.objects.all()))
    solvedissues=(len(Patient.objects.filter(Status="1"))+len(PatientIN.objects.filter(Status="1")))  
    unsolvedissues=(len(Patient.objects.filter(Status="3"))+len(PatientIN.objects.filter(Status="3")))
    pendingissues=totalfeedbacks-solvedissues-unsolvedissues
    return render(request,'Feedback/index2.html',{'totalfeedbacks':totalfeedbacks,'solvedissues':solvedissues,'pendingissues':pendingissues,'unsolvedissues':unsolvedissues})
=======
    return render(request,'Feedback/index2.html')
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32



def patientcomplaints(request):
    if request.session.get('user_session',None):
        currentuser=request.session['user_session']
        in_Minister=Minister.objects.filter(email=currentuser)
        in_HOD=HOD.objects.filter(email=currentuser)
        if in_Minister.exists():
            patientlist=Patient.objects.filter(Status="2")
        elif in_HOD.exists():
            patientlist=Patient.objects.filter(Status="0")
        return render(request,"Feedback/OUTPatientdash.html",{'patientlist':patientlist})
    else:
        return render(request,"Feedback/login.html")

def patientINcomplaints(request):
    if request.session.get('user_session',None):
        currentuser=request.session['user_session']
        in_Minister=Minister.objects.filter(email=currentuser)
        in_HOD=HOD.objects.filter(email=currentuser)
        if(in_Minister.exists()):
            patientlist=PatientIN.objects.filter(Status="2")
        elif(in_HOD.exists()):
            patientlist=PatientIN.objects.filter(Status="0")
        
        return render(request,"Feedback/INPatientdash.html",{'patientlist':patientlist})
    else:
        return render(request,"Feedback/login.html")

def change(request,patient_id):
    patient_el=Patient.objects.get(mobile_number=patient_id)
    patient_el.Status="1"
    patient_el.save()
    return HttpResponseRedirect(reverse('patientcomplaints'))

def change2(request,patient_id):
    patient_el=PatientIN.objects.get(mobile_number=patient_id)
    patient_el.Status="1"
    patient_el.save()
    return HttpResponseRedirect(reverse('patientINcomplaints'))


def forward(request,patient_id):
    patient_el=Patient.objects.get(mobile_number=patient_id)
    patient_el.Status="2"
    patient_el.save()
    return HttpResponseRedirect(reverse('patientcomplaints'))

def forward2(request,patient_id):
    patient_el=PatientIN.objects.get(mobile_number=patient_id)
    patient_el.Status="2"
    patient_el.save()
    return HttpResponseRedirect(reverse('patientINcomplaints'))



def dashboard(request):
    values=len(Patient.objects.filter(AreaofIssue="hygiene"))
    values1=len(Patient.objects.filter(AreaofIssue="doctor"))
    values2=len(Patient.objects.filter(AreaofIssue="waiting"))
    values3=len(Patient.objects.filter(AreaofIssue="pharmacy"))
    values4=len(Patient.objects.filter(AreaofIssue="nurse"))
    values5=len(PatientIN.objects.filter(AreaofIssue="admission"))
    values6=len(PatientIN.objects.filter(AreaofIssue="nurse"))
    values7=len(PatientIN.objects.filter(AreaofIssue="doctor"))
    values8=len(PatientIN.objects.filter(AreaofIssue="allot"))
    values9=len(PatientIN.objects.filter(AreaofIssue="discharge"))
    return render(request,'Feedback/dashboard.html',{'values':values,'values1':values1,'values2':values2,'values3':values3,'values4':values4,'values5':values5,'values6':values6,'values7':values7,'values8':values8,'values9':values})


def thankyou(request):
    return render(request,'Feedback/thankyou.html')

def addHOD(request):
    if request.method=='POST':
        form=AdminCreationForm(request.POST)
        if form.is_valid():
            hod_email=form.cleaned_data['email']
            passwd=form.cleaned_data['password']
            record=HOD(email=hod_email,password=passwd)
            record.save()
            return HttpResponseRedirect(reverse('login'))         
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/HODSignUp.html',{'form':form,'field_error':field_error})
    else:
        form=AdminCreationForm()
    return render(request,'Feedback/HODSignUp.html',{'form':form})



def addMinister(request):
    if request.method=='POST':
        form=AdminCreationForm(request.POST)
        if form.is_valid():
            minister_email=form.cleaned_data['email']
            passwd=form.cleaned_data['password']
            record=Minister(email=minister_email,password=passwd)
            record.save()
            return HttpResponseRedirect(reverse('login'))         
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/MinisterSignUp.html',{'form':form,'field_error':field_error})
    else:
        form=AdminCreationForm()
    return render(request,'Feedback/MinisterSignUp.html',{'form':form})

<<<<<<< HEAD
def login(request): 
=======
def login(request):
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
    if request.method=='POST':
        form=UserLoginForm(request.POST)
        if form.is_valid():
            input_email=form.cleaned_data['email']
            passwd=form.cleaned_data['password']
            in_HOD=HOD.objects.filter(email=input_email,password=passwd)
            in_Minister=Minister.objects.filter(email=input_email,password=passwd)
            if in_HOD.exists():
                request.session['user_session']=input_email
                return HttpResponseRedirect(reverse('dashboard'))
            elif in_Minister.exists():
                request.session['user_session']=input_email
                return HttpResponseRedirect(reverse('dashboard'))
            else:
                no_account="Your account does not exists"
                return render(request,'Feedback/login.html',{'form':form,'no_account':no_account})         
        else:
            field_error="Invalid Fields"
            return render(request,'Feedback/login.html',{'form':form,'field_error':field_error})

    else:
        form=UserLoginForm()
    return render(request,'Feedback/login.html',{'form':form})


def askingpage(request):
    return render(request,"Feedback/askingpage.html")

def adminaskingpage(request):
    return render(request,"Feedback/adminaskingpage.html")

def patientfeedback(request):
    if request.method=='POST':
        form=PatientCreationForm(request.POST)
        if form.is_valid():
            digits="0123456789"
            OTPcode=""
            for i in range(4) : 
                OTPcode += digits[math.floor(random.random() * 10)]
            user=form.cleaned_data['mobile_number']
<<<<<<< HEAD
            ip=form.cleaned_data['ip_number']
            request.session['user_session']=user
            currentuser=request.session['user_session']
            record=Patient(mobile_number=user,otp=OTPcode,ip_number=ip)
            record.save()   
=======
            request.session['user_session']=user
            currentuser=request.session['user_session']
            checksOUT=Patient.objects.filter(mobile_number=currentuser)
            checksIN=PatientIN.objects.filter(mobile_number=currentuser)
            if checksOUT.exists():
                had_error="You have already submitted the feedback"
                return render(request,'Feedback/feedbackstart.html',{'form':form,'had_error':had_error})
            elif checksIN.exists():
                had_error="You have already submitted the feedback"
                return render(request,'Feedback/feedbackstart.html',{'form':form,'had_error':had_error})
            record=Patient(mobile_number=user,otp=OTPcode)
            record.save()
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
            send_mail('OTP for ESIC',
            'Your One Time Password is'+OTPcode,
            '',
            [user])
            return HttpResponseRedirect(reverse('verifyotp'))
        else:
            field_error="Please Check Your Fields"
            return render(request,'Feedback/feedbackstart.html',{'form':form,'field_error':field_error})
    else:
        form=PatientCreationForm()
    return render(request,'Feedback/feedbackstart.html',{'form':form})

def patientINfeedback(request):
    if request.method=='POST':
        form=PatientCreationForm(request.POST)
        if form.is_valid():
            digits="0123456789"
            OTPcode=""
            for i in range(4): 
                OTPcode += digits[math.floor(random.random() * 10)]
            user=form.cleaned_data['mobile_number']
            request.session['user_session']=user
            currentuser=request.session['user_session']
            checksOUT=Patient.objects.filter(mobile_number=currentuser)
            checksIN=PatientIN.objects.filter(mobile_number=currentuser)
            if checksOUT.exists():
                had_error="You have already submitted the feedback"
                return render(request,'Feedback/feedbackinstart.html',{'form':form,'had_error':had_error})
            elif checksIN.exists():
                had_error="You have already submitted the feedback"
                return render(request,'Feedback/feedbackinstart.html',{'form':form,'had_error':had_error})
            record=PatientIN(mobile_number=user,otp=OTPcode)
            record.save()
            send_mail('OTP for ESIC',
            'Your One Time Password is: '+OTPcode,
            '',
            [user])

Feedback/templates/Feedback/INPatientdash.html
{% extends 'Feedback/base2.html' %}
{% block title %}
Inpatient Issues
{% endblock %}

{% block body %}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Unsolved In Patient Issues</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Search for Area of Issue,</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Patient Email ID</th>
                <th>Rating</th>
                <th>Self/Family</th>
                <th>Department</th>
                <th>Issue In</th>
                <th>View</th>
                <th>Click If Solved</th>
                <th>Click to forward</th>                  
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Patient Email ID</th>
                <th>Rating</th>
                <th>Self/Family</th>
                <th>Department</th>
                <th>Issue In</th>
                <th>View</th>
                <th>Click If Solved</th>
                <th>Click to forward</th>                  

              </tr>
            </tfoot>
            <tbody>
            
             {% for patient in patientlist %}
              <tr>
                <td>{{ patient.mobile_number }}</td>
                <td>{{ patient.Rating }}</td>
                <td>{{ patient.sandf }}</td>
                <td>{{ patient.department }}</td>
                <td>{{ patient.AreaofIssue }}</td>
                <td>
                  <a href="{% url 'ch' patient.mobile_number %}" class="btn btn-success btn-icon-split">
                      <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                      </span>
                      <span class="text">Click</span>
                  </a>
                  </td>
                <td>
                <a href="{% url 'change2' patient.mobile_number %}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Click</span>
                </a>
                </td>
                <td>
                  <a href="{% url 'forward2' patient.mobile_number %}" class="btn btn-danger btn-icon-split">
                      <span class="icon text-white-50">
                        <i class="fas fa-check"></i>
                      </span>
                      <span class="text">Click</span>
                  </a>
                </td>
              </tr>
             {% endfor %}
            
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
{% endblock %}

Feedback/templates/Feedback/MinisterSignUp.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ESIC - SignUp</title>

  <!-- Custom fonts for this template-->
  {% load static %}
  <link href="{% static 'Feedback/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'Feedback/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row">
          <div class="col-lg-5 d-none d-lg-block bg-register-imag">
            <div align="center" style="padding-top:20px;">
            <img src="{% static 'Feedback/img/ESIC.png' style='padding-left:20px;' %}">
          </div>
          </div>
          <div class="col-lg-7">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4">Create an Account!</h1>
              </div>
              <form action="" class="user" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <p style="color:red;">{{ field_errors }}</p>

                <div class="form-group">
                  <input id="id_email" class="form-control form-control-user" type="email"  name="email"  required placeholder="Enter Your Email ID">
                </div>
                <div class="form-group">
                  <input type="password" name="password" class="form-control form-control-user" id="id_password" required placeholder="Enter a password">
                </div>
               
                <button type="submit" class="btn btn-primary btn-user btn-block">
                  Submit
                </button>
                
              </form>
              <hr>
              
              <div class="text-center">
                <a class="small" href="#">Already have an account? Login!</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'Feedback/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'Feedback/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

Feedback/templates/Feedback/OutPatientdash.html
{% extends 'Feedback/base2.html' %}
{% block title %}
OUTPatient Issues
{% endblock %}

{% block body %}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Unsolved Out Patient Issues</h1>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">Search for Area of Issue ,Patient IDetc.,</h6>
      </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Patient Email ID</th>
                <th>Rating</th>
                <th>Self/Family</th>
                <th>Department</th>
                <th>Issue In</th>
                <th>Click If Solved</th>  
                <th>Click to forward</th>             
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Patient Email ID</th>
                <th>Rating</th>
                <th>Self/Family</th>
                <th>Department</th>
                <th>Issue In</th>
                <th>Click If Solved</th>
                <th>Click to forward</th>
                
              </tr>
            </tfoot>
            <tbody>
            
             {% for patient in patientlist %}
              <tr>
                <td>{{ patient.mobile_number }}</td>
                <td>{{ patient.Rating }}</td>
                <td>{{ patient.sandf }}</td>
                <td>{{ patient.department }}</td>
                <td>{{ patient.AreaofIssue }}</td>
                <td>
               <a href="{% url 'change' patient.mobile_number %}" class="btn btn-success btn-icon-split">
                    <span class="icon text-white-50">
                      <i class="fas fa-check"></i>
                    </span>
                    <span class="text">Click</span>
                </a>
                </td>
                <td>
                  <a href="{% url 'forward' patient.mobile_number %}" class="btn btn-danger btn-icon-split">
                       <span class="icon text-white-50">
                         <i class="fas fa-check"></i>
                       </span>
                       <span class="text">Click</span>
                   </a>
                   </td>
              </tr>
             {% endfor %}
            
            </tbody>
          </table>
        </div>
      </div>
    </div>

  </div>
  <!-- /.container-fluid -->

</div>
{% endblock %}

Feedback/templates/Feedback/feedbackstart.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>ADMIN - Login</title>

  <!-- Custom fonts for this template-->
  {% load static %}
  <link href="{% static 'Feedback/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template-->
  <link href="{% static 'Feedback/css/sb-admin-2.min.css' %}" rel="stylesheet">

</head>

<body class="bg-gradient-primary">

  <div class="container">

    <!-- Outer Row -->
    <div class="row justify-content-center">

      <div class="col-xl-6 col-lg-12 col-md-3">

        <div class="card o-hidden border-0 shadow-lg my-5">
          <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
              
              <div class="col-lg-12">
                <div class="p-5">
                  <div class="text-center">
<<<<<<< HEAD
                    <h1 class="h4 text-gray-900 mb-4">Enter your details here</h1>
=======
                    <h1 class="h4 text-gray-900 mb-4">Please provide your Feedback</h1>
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
                  </div>
                  <form  method="POST" class="user" action="" enctype="multipart/form-data">
                    {% csrf_token %}
                     <p style="color: red;">{{ field_error }}</p>
                     <p style="color: red;">{{ had_error }}</p>
    
                     <br>
                     <br>
<<<<<<< HEAD
                     <div class="form-group">
                      <input type="email" id="id_mobile_number" class="form-control form-control-user" name="mobile_number" placeholder="Enter Your Email ">
                     </div>
                     <br>
                     
                     <div class="form-group">
                     <input type="text" id="id_ip_number" class="form-control form-control-user" name="ip_number" placeholder="Enter Your IP number">
                    </div>
                    
                     <br>
                     <div align="center">
                     <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                     <div class="g-recaptcha" data-sitekey="6LfCS9kUAAAAAMa0VzzJWWImOJqxHWwiSkL7iPvp"></div>
                    </div>
=======
                    
                     <input type="email" id="id_mobile_number" class="form-control form-control-user" name="mobile_number" placeholder="Enter Your email address">
                    
                     <br>
                     
                     <script src="https://www.google.com/recaptcha/api.js" async defer></script>
                     &nbsp;&nbsp;&nbsp;&nbsp;<div class="g-recaptcha" data-sitekey="6LfCS9kUAAAAAMa0VzzJWWImOJqxHWwiSkL7iPvp"></div>
>>>>>>> 01b223460a761091531d1b4af2d88e5599152d32
                     <br>
                     <button type="submit" class="btn btn-primary btn-user btn-block">
                      Continue
                    </button>
                  
                  </form>
                  <hr>
                  
                </div>
              </div>
            </div>
          </div>
        </div>

      </div>

    </div>

  </div>

  <!-- Bootstrap core JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'Feedback/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Core plugin JavaScript-->
  <script src="{% static 'Feedback/vendor/jquery-easing/jquery.easing.min.js' %}"></script>

  <!-- Custom scripts for all pages-->
  <script src="{% static 'Feedback/js/sb-admin-2.min.js' %}"></script>

</body>

</html>

Feedback/templates/Feedback/otp.html
<html>
<head>

</head>
<body>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <p>Enter Email</p>
    <input type="email" id="id_email_id" name="email_id" placeholder="enter email">
    <button type="submit">Submit</button>

</form>

</body>
</html>